version: '3.8'

services:
  api-gateway:
    image: fernando1983mn/api-gateway:1.0.0
    container_name: api-gateway
    ports:
      - "9000:9000"
    environment:
      - SERVER_PORT=9000
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET:-mySuperSecretKeyForJwtGenerationThatIsAtLeast32CharactersLong!}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    extra_hosts:
      - "redis:host-gateway"
    depends_on:
      - redis
    networks:
      - gateway-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - gateway-network
    volumes:
      - redis-data:/data

networks:
  gateway-network:
    driver: bridge

volumes:
  redis-data: